### ISSUE TITLE
Need to aquire a test set after training the model - progress updates in comments

### ISSUE THREAD

**Issue by AnushaChattoHeidelberg** [AnushaChattoHeidelberg/PredictFinancialMarketsByAnalyzingSpeechByCentralBanksAnalyzing#1]

**Comment by AnushaChattoHeidelberg** [comment]
updates so far, article set found on kaggle, but all articles don't have market dates available, need to filter accordingly

**Comment by AnushaChattoHeidelberg** [comment]
vix market data found, added to repo, pull request created

**Comment by AnushaChattoHeidelberg** [comment]
raw data table created, scrips used to process added into snippets and data stored in data folders

**Comment by keerthan-ugrani** [comment]
Data has been converted to embeddings and tested against the same model as used in training and testing the BERT transformed data
